"""002 create geography tables

Revision ID: 797d1297f7a7
Revises: 90d73468a824
Create Date: 2026-10-06 19:12:04.316217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '797d1297f7a7'
down_revision: Union[str, Sequence[str], None] = '90d73468a824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('code', sa.String(length=10), nullable=False, comment='Código corto del estado (CDMX, NL, JAL, ...)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre completo del estado'),
    sa.Column('region', sa.Enum('CENTRO', 'NORTE', 'OCCIDENTE', 'SUR', name='region_type'), nullable=False, comment='Región geográfica del estado'),
    sa.Column('income_group', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='income_group_type'), nullable=False, comment='Grupo de ingreso relativo (HIGH/MEDIUM/LOW)'),
    sa.Column('population_share', sa.Numeric(precision=6, scale=4), nullable=False, comment='Share relativo de población (0.0000–1.0000)'),
    sa.Column('income_index', sa.Numeric(precision=5, scale=2), nullable=False, comment='Índice de ingreso relativo (1.00 = promedio)'),
    sa.Column('online_penetration', sa.Numeric(precision=5, scale=4), nullable=False, comment='Penetración online (0.0000–1.0000)'),
    sa.Column('regional_factor', sa.Numeric(precision=5, scale=4), nullable=False, comment='Factor regional de demanda (1.00 = promedio)'),
    sa.Column('growth_rate', sa.Numeric(precision=5, scale=4), nullable=False, comment='Growth rate anual (0.04 = +4%)'),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='record_status', create_type=False), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('code = UPPER(code)', name='states_code_upper'),
    sa.CheckConstraint('income_index > 0', name='states_income_index_positive'),
    sa.CheckConstraint('online_penetration >= 0 AND online_penetration <= 1', name='states_online_penetration_range'),
    sa.CheckConstraint('population_share >= 0 AND population_share <= 1', name='states_population_share_range'),
    sa.CheckConstraint('regional_factor > 0', name='states_regional_factor_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_states_income_group', 'states', ['income_group'], unique=False)
    op.create_index('ix_states_region', 'states', ['region'], unique=False)
    op.create_index('ix_states_status', 'states', ['status'], unique=False)
    op.create_table('locations',
    sa.Column('code', sa.String(length=30), nullable=False, comment='Código de la ubicación (CEDIS-CDMX, STORE-CDMX-01, ...)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre legible de la ubicación'),
    sa.Column('location_type', sa.Enum('CEDIS', 'STORE', name='location_type'), nullable=False, comment='Tipo de ubicación: CEDIS o STORE'),
    sa.Column('state_id', sa.UUID(), nullable=False),
    sa.Column('capacity_units', sa.Integer(), server_default='0', nullable=False, comment='Capacidad máxima en unidades (0 = sin límite en V1)'),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='record_status', create_type=False), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity_units >= 0', name='locations_capacity_nonnegative'),
    sa.CheckConstraint('code = UPPER(code)', name='locations_code_upper'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_locations_state', 'locations', ['state_id'], unique=False)
    op.create_index('ix_locations_status', 'locations', ['status'], unique=False)
    op.create_index('ix_locations_type', 'locations', ['location_type'], unique=False)
    op.create_table('state_category_affinity',
    sa.Column('state_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('affinity_factor', sa.Numeric(precision=5, scale=4), server_default='1.0', nullable=False, comment='Factor de afinidad (1.0 = neutro)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('affinity_factor >= 0.5 AND affinity_factor <= 1.5', name='affinity_factor_range'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_id', 'category_id', name='affinity_unique_state_category')
    )
    op.create_index('ix_affinity_category', 'state_category_affinity', ['category_id'], unique=False)
    op.create_index('ix_affinity_state', 'state_category_affinity', ['state_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_affinity_state', table_name='state_category_affinity')
    op.drop_index('ix_affinity_category', table_name='state_category_affinity')
    op.drop_table('state_category_affinity')
    op.drop_index('ix_locations_type', table_name='locations')
    op.drop_index('ix_locations_status', table_name='locations')
    op.drop_index('ix_locations_state', table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_states_status', table_name='states')
    op.drop_index('ix_states_region', table_name='states')
    op.drop_index('ix_states_income_group', table_name='states')
    op.drop_table('states')
    # ### end Alembic commands ###