"""001 create catalog tables

Revision ID: 90d73468a824
Revises: 
Create Date: 2026-10-06 17:20:57.494978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d73468a824'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('code', sa.String(length=20), nullable=False, comment='Código corto en mayúsculas (PLAYERAS, SUDADERAS, ...)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre legible de la categoría'),
    sa.Column('department', sa.Enum('APPAREL', 'FOOTWEAR', 'EQUIPMENT', 'ACCESSORIES', name='department_type'), nullable=False, comment='Departamento al que pertenece'),
    sa.Column('seasonality', sa.Enum('NONE', 'WINTER', 'NEW_YEAR', 'SUMMER', name='seasonality_type'), server_default='NONE', nullable=False, comment='Patrón estacional mensual de la categoría'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='record_status'), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('code = UPPER(code)', name='categories_code_upper'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_categories_department', 'categories', ['department'], unique=False)
    op.create_index('ix_categories_status', 'categories', ['status'], unique=False)
    op.create_table('products',
    sa.Column('style_code', sa.String(length=30), nullable=False, comment='Código de estilo: {CAT}-{SEG}-{NNNN}'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Nombre comercial del producto'),
    sa.Column('segment', sa.Enum('WOMEN', 'MEN', 'KIDS', 'UNISEX', name='segment_type'), nullable=False, comment='Segmento demográfico del producto'),
    sa.Column('age_group', sa.Enum('ADULT', 'KIDS', name='age_group_type'), nullable=False, comment='Grupo de edad objetivo'),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('sport', sa.Enum('RUNNING', 'TRAINING', 'FUTBOL', 'BASKET', 'CASUAL', 'YOGA', 'GENERAL', name='sport_type'), server_default='GENERAL', nullable=False, comment='Deporte principal'),
    sa.Column('branded', sa.Boolean(), server_default='false', nullable=False, comment='Lleva la cara de Rikochet (producto estrella)'),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio de lista en MXN, terminado en .99'),
    sa.Column('base_cost', sa.Numeric(precision=10, scale=2), nullable=False, comment='Costo de referencia en MXN (no el de compra real)'),
    sa.Column('demand_profile', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NICHE', name='demand_profile_type'), nullable=False, comment='Perfil de demanda (HIGH, MEDIUM, LOW, NICHE)'),
    sa.Column('lifecycle_stage', sa.Enum('LAUNCH', 'GROWTH', 'MATURE', 'DECLINE', 'DISCONTINUED', name='lifecycle_stage_type'), server_default='MATURE', nullable=False, comment='Etapa actual del ciclo de vida'),
    sa.Column('launch_date', sa.Date(), nullable=False, comment='Fecha simulada de lanzamiento'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='record_status'), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(segment = 'KIDS'   AND age_group = 'KIDS')  OR (segment = 'WOMEN'  AND age_group = 'ADULT') OR (segment = 'MEN'    AND age_group = 'ADULT') OR (segment = 'UNISEX' AND age_group IN ('ADULT', 'KIDS'))", name='products_age_group_coherent'),
    sa.CheckConstraint('base_cost > 0', name='products_cost_positive'),
    sa.CheckConstraint('base_price > 0', name='products_price_positive'),
    sa.CheckConstraint('base_price > base_cost', name='products_margin_positive'),
    sa.CheckConstraint('style_code = UPPER(style_code)', name='products_style_upper'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_code')
    )
    op.create_index('ix_products_category', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_demand', 'products', ['demand_profile'], unique=False)
    op.create_index('ix_products_lifecycle', 'products', ['lifecycle_stage'], unique=False)
    op.create_index('ix_products_segment', 'products', ['segment'], unique=False)
    op.create_index('ix_products_status', 'products', ['status'], unique=False)
    op.create_table('product_variants',
    sa.Column('sku', sa.String(length=50), nullable=False, comment='Código SKU: {style_code}-{size}-{color}'),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False, comment='Talla: XS–XXL, 4–14 (kids), 24–30 (tenis), OS, etc.'),
    sa.Column('color', sa.Enum('BLK', 'WHT', 'GRY', 'NVY', 'RED', 'BLU', 'GRN', 'PNK', 'YLW', name='color_code'), nullable=False, comment='Color de la variante'),
    sa.Column('barcode', sa.String(length=20), nullable=False, comment='EAN-13 simulado'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='record_status'), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(size) > 0', name='variants_size_nonempty'),
    sa.CheckConstraint('sku = UPPER(sku)', name='variants_sku_upper'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('product_id', 'size', 'color', name='variants_sku_unique_per_product'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('ix_variants_color', 'product_variants', ['color'], unique=False)
    op.create_index('ix_variants_product', 'product_variants', ['product_id'], unique=False)
    op.create_index('ix_variants_size', 'product_variants', ['size'], unique=False)
    op.create_index('ix_variants_status', 'product_variants', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_variants_status', table_name='product_variants')
    op.drop_index('ix_variants_size', table_name='product_variants')
    op.drop_index('ix_variants_product', table_name='product_variants')
    op.drop_index('ix_variants_color', table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('ix_products_status', table_name='products')
    op.drop_index('ix_products_segment', table_name='products')
    op.drop_index('ix_products_lifecycle', table_name='products')
    op.drop_index('ix_products_demand', table_name='products')
    op.drop_index('ix_products_category', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_categories_status', table_name='categories')
    op.drop_index('ix_categories_department', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
